version: '3.9'

services:
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    tty: true
    networks:
      - backend
    command: bash -c "/app/scripts/init.sh && cargo watch -x run"

  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: 'newsletter'
      TZ: 'Asia/Tokyo'
    hostname: localhost
    restart: always
    user: postgres
    networks:
      - backend

networks:
  backend:
    external: false

volumes:
  db_data:
    external: false
